spring:
  application:
    name: StudentApp

  datasource:
    url: jdbc:postgresql://localhost:5432/studentdb  
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

logging:
  level:
    "[org.hibernate.SQL]": DEBUG


server:
  port: 8080
